name            = Semver Library
description     = A library for Semver-related features.
version         = 1.0.0

url             = https://github.com/Akazukin-Team/Java-Semver-Library

vendor          = Akazukin Team
vendor-url      = https://github.com/Akazukin-Team

groupId         = org.akazukin
artifactId      = semver

archiveBaseName = Semver
